#!/bin/sh

# Add the following lines to /etc/rc.conf to enable iohyve:
#
# iohyve_enable="YES"
#
# PROVIDE: iohyve
# REQUIRE: LOGIN sshd
#

. /etc/rc.subr

name="iohyve"
rcvar=iohyve_enable

# read configuration and set defaults
load_rc_config "$name"
: ${iohyve_enable="NO"}

start_cmd="iohyve_start"
stop_cmd="iohyve_stop"

iohyve_start()
{
	guestlist="$(zfs list -H -t volume -o name | grep iohyve | grep disk0 | cut -d'/' -f3)"
	for i in $guestlist ; do
		pool="$(zfs list -H -t volume -o name | grep iohyve | grep $i | grep disk0 | cut -d'/' -f1-3)"
		bootprop="$(zfs get -H -o value iohyve:boot $pool)"
		if [ $bootprop = "1" ]; then
			/usr/local/sbin/iohyve start $i
		fi
	done
}

iohyve_stop()
{
	/usr/local/sbin/iohyve scram
}

run_rc_command "$1"
