#!/bin/sh

# iohyve v0.7.3 2016/01/08 "Bear in a Datacenter Edition"

# Set proper path thanks to iocage
PATH=${PATH}:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin

# See whether given command is readonly
# and therefore doesn't need root credentials
__readonly_cmd () {
    case "$1" in
        help|-h|activetaps|conlist|fwlist|get|getall|info|isolist|list|snaplist|taplist|version) echo "0"
            ;;
        *) echo "1"
            ;;
    esac
}

# Process command line
__parse_cmd () {
  while [ $# -gt 0 ] ; do
    case "$1" in
      version)  __version
                exit
      ;;
      oldset)	__oldset "$@"
                exit
      ;;
      setup)    __setup "$@"
                exit
      ;;
      list)     __list
                exit
      ;;
      info)	__info "$@"
		exit
      ;;
      isolist)  __isolist
                exit
      ;;
      fwlist)	__fwlist
                exit
      ;;
      fetch)    __fetch "$@"
                exit
      ;;
      cpiso)	__cpiso "$@"
		exit
      ;;
      renameiso) __renameiso "$@"
                exit
      ;;
      rmiso) 	__deleteiso "$@"
                exit
      ;;
      fetchfw)	__fetchfw "$@"
                exit
      ;;
      cpfw)	__cpfw "$@"
                exit
      ;;
      renamefw) __renamefw "$@"
                exit
      ;;
      rmfw)	__deletefw "$@"
                exit
      ;;
      create)   __create "$@"
                exit
      ;;
      install)  __install "$@"
                exit
      ;;
      load)     __load "$2" "$3"
                exit
      ;;
      boot)     __boot "$2" "$3" "$4"
                exit
      ;;
      start)    __start "$@"
                exit
      ;;
      uefi)	__uefi "$@"
		exit
      ;;
      stop)     __stop "$@"
                exit
      ;;
      forcekill) __forcekill "$@"
                exit
      ;;
      scram)    __scram
                exit
      ;;
      destroy)  __destroy "$@"
                exit
      ;;
      rename)   __rename "$@"
                exit
      ;;
      delete)   __delete "$@"
                exit
      ;;
      set)      __set "$@"
                exit
      ;;
      get)      __get "$@"
                exit
      ;;
      rmpci)	__rmpci "$@"
		exit
      ;;
      getall)   __getall "$@"
                exit
      ;;
      fix-bargs) __fixbargs "$@"
		exit
      ;;
      add)	__add "$@"
		exit
      ;;
      remove)	__remove "$@"
		exit
      ;;
      resize)   __resize "$@"
                exit
      ;;
      disks)	__disks "$@"
		exit
      ;;
      snap)	__snapguest "$@"
		exit
      ;;
      roll)	__rollguest "$@"
		exit
      ;;
      clone)	__cloneguest "$@"
		exit
      ;;
      snaplist)	__snaplist
		exit
      ;;
      taplist)  __taplist
                exit
      ;;
      activetaps) __activetaps
                exit
      ;;
      conlist)  __conlist
                exit
      ;;
      console)  __console "$@"
                exit
      ;;
      conreset) __conreset
                exit
      ;;
      help|-h)  __help
                exit
      ;;
    esac
    shift
  done
}

# Show version
__version() {
	echo "iohyve v0.7.3 2016/01/08 Bear in a Datacenter Edition"
}

# Setup iohyve
__setup() {
	local args="$@"
	for arg in $args; do
		if [ $arg != "setup" ]; then
			local prop="$(echo $arg | cut -d '=' -f1)"
			local val="$(echo $arg | cut -d '=' -f2)"
			if [ $prop = "pool" ]; then
				local pool="$val"
				echo "Setting up iohyve pool..."
				zfs create $pool/iohyve
				# iohyve is already setup on a pool
				if [ -d /iohyve/ISO ]; then
					echo "Secondary pool set up..."
					zfs set mountpoint="/iohyve/$pool" $pool/iohyve
				# iohyve is not set up yet
				else
					zfs set mountpoint="/iohyve" $pool/iohyve
					zfs create $pool/iohyve/ISO
					zfs create $pool/iohyve/Firmware
				fi
			elif [ $prop = "kmod" ]; then
				if [ $val = "1" ]; then
					echo "Loading kernel modules..."
					kldload vmm
					kldload nmdm
				elif [ $val = "0" ]; then
					echo "Unloading kernel modules..."
					kldunload vmm
					kldunload nmdm
				else
					echo "Improper syntax"
					echo "kmod=1 to load modules"
					echo "kmod=0 to unload modules"
				fi
			elif [ $prop = "net" ]; then
				local bridgeif="$('ifconfig' -a | grep bridge0: | cut -c1-6)"
				if [ -z $bridgeif ]; then
					echo "Seting up bridge0 on $val..."
					ifconfig tap0 create
					sysctl net.link.tap.up_on_open=1
					ifconfig bridge0 create
					ifconfig bridge0 addm $val addm tap0
					ifconfig bridge0 up
				else
					echo "bridge0 is already enabled on this machine..."
				fi
			fi
		fi
	done
}

__get_bhyve_cmd() {
	local devices="$1"
	local pci_slot_count=0
	for device in $devices ; do
		echo "-s $pci_slot_count,$device"
		pci_slot_count=$(( pci_slot_count + 1 ))
	done
}

# Get PCI device config from zfs
__get_zfs_pcidev_conf() {
	local pool="$1"
	local oldifs=$IFS
	#local pci
	IFS=$'\n'
	for pcidev in $(zfs get -H -o property,value all $pool | grep iohyve:pcidev: | sort )
	do
		echo $pcidev | cut -f2-
	done
	IFS=$oldifs
}

# List Guests
__list() {
	local pools="$(zfs list -H | grep iohyve | cut -d '/' -f 1 | uniq )"
	(
        printf "%s^%s^%s^%s^%s\n" "Guest" "VMM?" "Running" "rcboot?" "Description"
	for pool in $pools; do
            local guests="$(zfs list -H | grep iohyve | grep -Ev "disk|ISO|Firmware" | grep -i $pool | cut -f1 | cut -d'/' -f3 | sed 1d | uniq)"
            for g in $guests; do
		local vmm="/dev/vmm/ioh-$g"
		if [ -e $vmm ]; then
			vmm="YES"
		else
			vmm="NO"
		fi
		local running=$(pgrep -fx "bhyve: ioh-$g")
		if [ -z $running ]; then
			running="NO"
		else
			running="YES"
		fi
		local boot="$(zfs get -H -o value iohyve:boot $pool/iohyve/$g)"
		if [ $boot = '1' ]; then
			boot="YES"
		else
			boot="NO"
		fi
		local description="$(zfs get -H -o value iohyve:description $pool/iohyve/$g)"
                printf "%s^%s^%s^%s^%s\n" "$g" "$vmm" "$running" "$boot" "$description"
            done
	done
	) | column -ts^
}

# Display info about all guests.
__info() {
	dflag="$2"
	if [ -z $dflag ]; then
		(printf 'Name\tSize\tRAM\tCPU\tOS\tLoader\n';  \
			zfs list -H -o name,volsize,iohyve:ram,iohyve:cpu,iohyve:os,iohyve:loader | \
			grep iohyve | grep -Ev "ISO|Firmware"  |  cut -d '/' -f3- | sed 1d) | column -t
	elif [ $dflag = "-d" ]; then
		(printf 'Name\tSize\tRAM\tCPU\tOS\tLoader\tDescription\n';  \
			zfs list -H -o name,volsize,iohyve:ram,iohyve:cpu,iohyve:os,iohyve:loader,iohyve:description | \
			grep iohyve | grep -Ev "ISO|Firmware"  |  cut -d '/' -f3- | sed 1d) | column -t
	else
		echo "Invalid flag..."
	fi
}

# List iso's
__isolist() {
	echo "Listing ISO's..."
	zfs list -H | grep iohyve/ISO | cut -f 1 | cut -d '/' -f 4 | sed 1d
}

# List Firmware
__fwlist() {
	echo "Listing Firmware..."
	zfs list -H | grep iohyve/Firmware | cut -f1 | cut -d '/' -f 4 | sed 1d
}

# Fetch ISO
__fetch() {
	local url="$2"
	local pool="$(zfs list -H | grep iohyve | cut -d '/' -f 1 | head -n1)"
	local name="$(basename $2)"
	echo "Fetching $url..."
	zfs create $pool/iohyve/ISO/$name
	fetch $url -o /iohyve/ISO/$name
}

# Copy ISO from local machine
__cpiso() {
	local loc="$2"
	local pool="$(zfs list -H | grep iohyve | cut -d '/' -f 1 | head -n1)"
	local name="$(basename $loc)"
	echo "Copying $name from $loc..."
	zfs create $pool/iohyve/ISO/$name
	cp $loc /iohyve/ISO/$name
}

# Rename an ISO
__renameiso() {
	local pool="$(zfs list -H | grep iohyve | cut -d '/' -f 1 | head -n1)"
	local iso="$2"
	local name="$3"
	echo "Renaming ISO $2 to $3..."
	mv /iohyve/ISO/$iso/$iso /iohyve/ISO/$iso/$name
	zfs rename $pool/iohyve/ISO/$iso $pool/iohyve/ISO/$name
}

# Delete ISO
__deleteiso() {
	local name="$2"
	local pool="$(zfs list -H | grep iohyve | cut -d '/' -f 1 | head -n1)"
	echo "Deleting $name..."
	zfs destroy $pool/iohyve/ISO/$name
}

# Fetch Firmware
__fetchfw() {
	local url="$2"
	local pool="$(zfs list -H | grep iohyve | cut -d '/' -f 1 | head -n1)"
	local name="$(basename $2)"
	echo "Fetching $url..."
	zfs create $pool/iohyve/Firmware/$name
	fetch $url -o /iohyve/Firmware/$name
}

# Copy Firmware from local machine
__cpfw() {
	local loc="$2"
	local pool="$(zfs list -H | grep iohyve | cut -d '/' -f 1 | head -n1)"
	local name="$(basename $loc)"
	echo "Copying $name from $loc..."
	zfs create $pool/iohyve/Firmware/$name
	cp $loc /iohyve/Firmware/$name
}

# Rename Firmware
__renamefw() {
	local pool="$(zfs list -H | grep iohyve | cut -d '/' -f 1 | head -n1)"
	local isfw="$2"
	local name="$3"
	echo "Renaming Firmware $2 to $3..."
	mv /iohyve/Firmware/$fw/$fw /iohyve/Firmware/$fw/$name
	zfs rename $pool/iohyve/Firmware/$fw $pool/iohyve/Firmware/$name
}

# Delete Firmware
__deletefw() {
	local name="$2"
	local pool="$(zfs list -H | grep iohyve | cut -d '/' -f 1 | head -n1)"
	echo "Deleting $name..."
	zfs destroy $pool/iohyve/Firmware/$name
}

# Create guest
__create() {
	local name="$2"
	local pool="${4-$(zfs list -H | grep iohyve | cut -d '/' -f 1 | head -n1)}"
	local size="$3"
	local description="$(date)"
	local guestlist="$(zfs list -H -o name -t volume | grep iohyve | cut -d'/' -f1-3)"
	listtaps(){
		for i in $guestlist ; do
			local tapprop="$(zfs get -H -o value iohyve:tap $i)"
			printf $tapprop'\n'
		done
	}
	local taplast="$(listtaps | sort -V | cut -c4- | tail -n1)"
	if [ -z $taplast ]; then
		local tap='0'
	else
		local tap="$(expr $taplast + 1)"
	fi
	listcons(){
		for i in $guestlist ; do
			local conprop="$(zfs get -H -o value iohyve:con $i)"
			printf $conprop'\n'
		done
	}
	local conlast="$(listcons | sort -V | cut -c5- | tail -n1)"
	if [ -z $conlast ]; then
		local con='0'
	else
		local con="$(expr $conlast + 1)"
	fi
	echo "Creating $name..."
	zfs create $pool/iohyve/$name
	zfs create -V $size -o volmode=dev $pool/iohyve/$name/disk0
	zfs set iohyve:name=$name $pool/iohyve/$name
	zfs set iohyve:size=$size $pool/iohyve/$name
	zfs set iohyve:ram=256M $pool/iohyve/$name
	zfs set iohyve:cpu=1 $pool/iohyve/$name
	zfs set iohyve:tap=tap$tap $pool/iohyve/$name
	zfs set iohyve:con=nmdm$con $pool/iohyve/$name
	zfs set iohyve:persist=1 $pool/iohyve/$name
	zfs set iohyve:boot=0 $pool/iohyve/$name
	zfs set iohyve:loader=bhyveload $pool/iohyve/$name
	zfs set iohyve:os=default $pool/iohyve/$name
	zfs set iohyve:autogrub='\n' $pool/iohyve/$name
	zfs set "iohyve:description=$description" $pool/iohyve/$name
	zfs set iohyve:bargs=-A_-H_-P $pool/iohyve/$name
}

# Install guest
__install() {
	local name="$2"
	local iso="$3"
	local pool="$(zfs list -H -t volume -o name | grep $name | grep disk0 | cut -d '/' -f1)"
	local dataset="$(zfs list -H -t volume | grep $name | cut -d '/' -f 1-3 | head -n1)"
	# Check if guest exists
	if [ -d /iohyve/$pool/$name ] || [ -d /iohyve/$name ]; then
		# Check to make sure guest isn't running
		local running=$(pgrep -fx "bhyve: ioh-$name")
		if [ -z $running ]; then
			local ram="$(zfs get -H -o value iohyve:ram $dataset)"
			local con="$(zfs get -H -o value iohyve:con $dataset)"
			local cpu="$(zfs get -H -o value iohyve:cpu $dataset)"
			local bargexist="$(zfs get -H -o value iohyve:bargs $dataset)"
			local bargs="$(echo $bargexist | sed -e 's/_/ /g')"
			echo "Installing $name..."
			# Set install prop
			zfs set iohyve:install=yes $pool/iohyve/$name
			# Load from CD
			__load "$name" "/iohyve/ISO/$iso/$iso"
			# Prepare and start guest
			pci="$(__prepare_guest $name) ahci-cd,/iohyve/ISO/$iso/$iso"
			local pci_args=$(__get_bhyve_cmd "$pci" )
			if [ $bargexist = '-' ]; then
				bhyve -c $cpu -A -H -P -m $ram $pci_args -lcom1,/dev/${con}A ioh-$name &
				echo "This version of your guest is outdated."
				echo "Please run iohyve fix-bargs guestname to update."
			else
				bhyve -c $cpu $bargs -m $ram $pci_args -lcom1,/dev/${con}A ioh-$name &
			fi
		else
			echo "Guest is already running."
		fi
	else
		echo "Not a valid guest name"
	fi
}

# Load guest
__load() {
	local name="$1"
	local media="$2"
	local disk="${3-$(zfs list -H -t volume -o name | grep $name | grep disk0 | head -n1)}"
	local dataset="$(zfs list -H -t volume -o name | grep $name | grep disk0 | cut -d '/' -f 1-3 | head -n1)"
	local ram="$(zfs get -H -o value iohyve:ram $dataset)"
	local con="$(zfs get -H -o value iohyve:con $dataset)"
	local loader="$(zfs get -H -o value iohyve:loader $dataset)"
	local install="$(zfs get -H -o value iohyve:install $dataset)"
	local os="$(zfs get -H -o value iohyve:os $dataset)"
	local autogrub="$(zfs get -H -o value iohyve:autogrub $dataset)"
    local bargexist="$(zfs get -H -o value iohyve:bargs $dataset)"
    local bargs="$(echo $bargexist | sed -e 's/_/ /g')"
    #Testing if -S is in the bargs settings. If then pass -S to bhyveload.
    local test_for_wire_memory="-S"
    case $bargs in
        *${test_for_wire_memory}*) local wire_memory="-S" ;;
        *) local wire_memory="" ;;
    esac
	if [ $loader = "grub-bhyve" ]; then
		if [ $install = "yes" ]; then
			if [ $os = "openbsd59" ]; then
				printf '\(hd0\)\ /dev/zvol/'$disk'\n' > /iohyve/$name/device.map
				printf '\(cd0\)\ '$media'\n' >> /iohyve/$name/device.map
				printf 'kopenbsd -h com0 /5.9/amd64/bsd.rd\nboot\n' | \
				grub-bhyve -m /iohyve/$name/device.map -r cd0 -M $ram ioh-$name > /dev/null
			elif [ $os = "openbsd58" ]; then
				printf '\(hd0\)\ /dev/zvol/'$disk'\n' > /iohyve/$name/device.map
				printf '\(cd0\)\ '$media'\n' >> /iohyve/$name/device.map
				printf 'kopenbsd -h com0 /5.8/amd64/bsd.rd\nboot\n' | \
				grub-bhyve $wire_memory -m /iohyve/$name/device.map -r cd0 -M $ram ioh-$name > /dev/null
			elif [ $os = "openbsd57" ]; then
				printf '\(hd0\)\ /dev/zvol/'$disk'\n' > /iohyve/$name/device.map
				printf '\(cd0\)\ '$media'\n' >> /iohyve/$name/device.map
				printf 'kopenbsd -h com0 /5.7/amd64/bsd.rd\nboot\n' | \
				grub-bhyve $wire_memory-m /iohyve/$name/device.map -r cd0 -M $ram ioh-$name > /dev/null
			elif [ $os = "netbsd" ]; then
				printf '\(hd0\)\ /dev/zvol/'$disk'\n' > /iohyve/$name/device.map
				printf '\(cd0\)\ '$media'\n' >> /iohyve/$name/device.map
				printf 'knetbsd -h -r cd0a /netbsd\nboot\n' | \
				grub-bhyve $wire_memory -m /iohyve/$name/device.map -r cd0 -M $ram ioh-$name > /dev/null
			elif [ $os = "debian" ]; then
				printf '\(hd0\)\ /dev/zvol/'$disk'\n' > /iohyve/$name/device.map
				printf '\(cd0\)\ '$media'\n' >> /iohyve/$name/device.map
				printf '\n' | \
				grub-bhyve $wire_memory-m /iohyve/$name/device.map -r cd0 -M $ram ioh-$name  > /dev/null
			elif [ $os = "d8lvm" ]; then
				printf '\(hd0\)\ /dev/zvol/'$disk'\n' > /iohyve/$name/device.map
				printf '\(cd0\)\ '$media'\n' >> /iohyve/$name/device.map
				printf '\n' | \
				grub-bhyve $wire_memory -m /iohyve/$name/device.map -r cd0 -M $ram ioh-$name  > /dev/null
			elif [ $os = "centos6" ]; then
				printf '\(hd0\)\ /dev/zvol/'$disk'\n' > /iohyve/$name/device.map
				printf '\(cd0\)\ '$media'\n' >> /iohyve/$name/device.map
				printf 'linux (cd0)/isolinux/vmlinuz\ninitrd (cd0)/isolinux/initrd.img\nboot\n' | \
				grub-bhyve $wire_memory -m /iohyve/$name/device.map -r cd0 -M $ram ioh-$name  > /dev/null
			elif [ $os = "arch" ]; then
				printf '\(hd0\)\ /dev/zvol/'$disk'\n' > /iohyve/$name/device.map
				printf '\(cd0\)\ '$media'\n' >> /iohyve/$name/device.map
				printf 'linux (cd0)/arch/boot/x86_64/vmlinuz archisobasedir=arch archisolabel=ARCH_'$(date +%Y%m)' ro\ninitrd (cd0)/arch/boot/x86_64/archiso.img\nboot\n' | \
				grub-bhyve $wire_memory -m /iohyve/$name/device.map -r cd0 -M $ram ioh-$name  > /dev/null
			else
				printf '\(hd0\)\ /dev/zvol/'$disk'\n' > /iohyve/$name/device.map
				printf '\(cd0\)\ '$media'\n' >> /iohyve/$name/device.map
				grub-bhyve $wire_memory -m /iohyve/$name/device.map -r cd0 -c /dev/${con}A -M $ram ioh-$name
			fi
		elif [ $install = "no" ]; then
			if [ $os = "openbsd59" ]; then
				printf '\(hd0\)\ /dev/zvol/'$disk'\n' > /iohyve/$name/device.map
				printf '\(cd0\)\ '$media'\n' >> /iohyve/$name/device.map
				printf 'kopenbsd -h com0 -r sd0a /bsd\nboot\n' | \
				grub-bhyve $wire_memory -m /iohyve/$name/device.map -r hd0,openbsd1 -M $ram ioh-$name  > /dev/null
			elif [ $os = "openbsd58" ]; then
				printf '\(hd0\)\ /dev/zvol/'$disk'\n' > /iohyve/$name/device.map
				printf '\(cd0\)\ '$media'\n' >> /iohyve/$name/device.map
				printf 'kopenbsd -h com0 -r sd0a /bsd\nboot\n' | \
				grub-bhyve -m /iohyve/$name/device.map -r hd0,openbsd1 -M $ram ioh-$name  > /dev/null
			elif [ $os = "openbsd57" ]; then
				printf '\(hd0\)\ /dev/zvol/'$disk'\n' > /iohyve/$name/device.map
				printf '\(cd0\)\ '$media'\n' >> /iohyve/$name/device.map
				printf 'kopenbsd -h com0 -r sd0a /bsd\nboot\n' | \
				grub-bhyve -m /iohyve/$name/device.map -r hd0,openbsd1 -M $ram ioh-$name  > /dev/null
			elif [ $os = "netbsd" ]; then
				printf '\(hd0\)\ /dev/zvol/'$disk'\n' > /iohyve/$name/device.map
				printf '\(cd0\)\ '$media'\n' >> /iohyve/$name/device.map
				printf 'knetbsd -h -r sd0a /netbsd\nboot\n' | \
				grub-bhyve $wire_memory -m /iohyve/$name/device.map -r hd0,msdos1 -M $ram ioh-$name  > /dev/null
			elif [ $os = "debian" ]; then
				printf '\(hd0\)\ /dev/zvol/'$disk'\n' > /iohyve/$name/device.map
				printf '\(cd0\)\ '$media'\n' >> /iohyve/$name/device.map
				printf '\n' | \
				grub-bhyve $wire_memory -m /iohyve/$name/device.map -r hd0,msdos1 -M $ram ioh-$name  > /dev/null
			elif [ $os = "d8lvm" ]; then
				printf '\(hd0\)\ /dev/zvol/'$disk'\n' > /iohyve/$name/device.map
				printf '\(cd0\)\ '$media'\n' >> /iohyve/$name/device.map
				printf '\n' | \
				grub-bhyve $wire_memory -m /iohyve/$name/device.map -r hd0,msdos1 -d /grub -M $ram ioh-$name  > /dev/null
			elif [ $os = "centos6" ]; then
				printf '\(hd0\)\ /dev/zvol/'$disk'\n' > /iohyve/$name/device.map
				printf '\(cd0\)\ '$media'\n' >> /iohyve/$name/device.map
				printf '\n' | \
				grub-bhyve $wire_memory -m /iohyve/$name/device.map -r hd0,msdos1 -d /grub -M $ram ioh-$name  > /dev/null
			elif [ $os = "custom" ]; then
				printf '\(hd0\)\ /dev/zvol/'$disk'\n' > /iohyve/$name/device.map
				printf '\(cd0\)\ '$media'\n' >> /iohyve/$name/device.map
				printf $autogrub | \
				grub-bhyve $wire_memory -m /iohyve/$name/device.map -r hd0,msdos1 -M $ram ioh-$name  > /dev/null
			else
				printf '\(hd0\)\ /dev/zvol/'$disk'\n' > /iohyve/$name/device.map
				printf '\(cd0\)\ '$media'\n' >> /iohyve/$name/device.map
				grub-bhyve $wire_memory -m /iohyve/$name/device.map -r hd0,msdos1 -c /dev/${con}A -M $ram ioh-$name
			fi
		fi
	else
		bhyveload $wire_memory -m $ram -d $media -c /dev/${con}A ioh-$name
	fi
}

# Boot guest
__boot() {
	local name="$1"
	# runmode (runonce/persist)
	#   0 = once
	#   1 = persist regular (stop if guest is powering off)
	#   2 = always persist (start again even if guest is powering off)
	local runmode="$2"
	local pci="$3"
	local dataset="$(zfs list -H -t volume | grep $name | grep disk0 | cut -d '/' -f 1-3 | head -n1)"
	local ram="$(zfs get -H -o value iohyve:ram $dataset)"
	local con="$(zfs get -H -o value iohyve:con $dataset)"
	local cpu="$(zfs get -H -o value iohyve:cpu $dataset)"
	local persist="$(zfs get -H -o value iohyve:persist $dataset)"
	local bargexist="$(zfs get -H -o value iohyve:bargs $dataset)"
	local bargs="$(echo $bargexist | sed -e 's/_/ /g')"
	# Set install prop
	zfs set iohyve:install=no $dataset
	# Generate list of bhyve -s commands for all devices
	local pci_args=$(__get_bhyve_cmd "$pci" )
	# Handle the starting of the guest inside a spawned subshell so the guest
	# can be restarted automatically if the guest reboots or crashes
	local runstate="1"
	(
		while [ $runstate = "1" ]
		do
			__load "$name" "/dev/zvol/$dataset/disk0"
			if [ $bargexist = '-' ]; then
				bhyve -c $cpu -A -H -P -m $ram $pci_args -lcom1,/dev/${con}A ioh-$name &
				echo "This version of your guest is outdated."
				echo "Please run iohyve fix-bargs guestname to update."
			else
				bhyve -c $cpu $bargs -m $ram $pci_args -lcom1,/dev/${con}A ioh-$name &
			fi
			local vmpid=$!
			wait $vmpid
			vmrc=$?
			sleep 5
			if [ $runmode == "0" ]; then
				runstate="0"
			elif [ $vmrc == "1" ] && [ $runmode != 2 ]; then
				# VM has been powered off
				runstate="0"
			else
				if [ $(zfs get -H -o value iohyve:persist $dataset) != 1 ]; then
					runstate="0"
				fi
			fi
		done
		bhyvectl --destroy --vm=ioh-$name
		# Resetting the flag so that a vm which we stopped by abusing zfs set/get
		# as as an IPC mechanism is persistent again next time we start it
		if [ ! -z $persist ]; then
			zfs set iohyve:persist="$persist" $dataset
		fi
	) &
}

__prepare_guest() {
	local name="$1"
	local dataset="$(zfs list -H -t volume | grep $name | grep disk0 | cut -d '/' -f 1-3 | head -n1)"
	local pci="$(__get_zfs_pcidev_conf $dataset)"
	local tap="$(zfs get -H -o value iohyve:tap $dataset)"
	local mac="$(zfs get -H -o value iohyve:mac $dataset)"
	# Setup tap if needed
	if [ $tap ] && [ $tap != "-" ]; then
		if [ $tap != "tap0" ]; then
			# no need to create tap0, should be installed already via README
			# check to see if tap is already created before attempting to create new tap interface
			# Simple hacky check for tapif
			local tapif="$('ifconfig' -l | grep $tap | cut -c1)"
			if [ -z $tapif ]; then
				# create tap interface
				ifconfig $tap create
				ifconfig bridge0 addm $tap
			fi
		fi
		# Add a virtio-net pci device for the tap
		if [ $mac = "-" ]; then
			pci="virtio-net,$tap $pci"
		else
			pci="virtio-net,${tap},mac=${mac} $pci"
		fi
	fi
	#Add disk as second PCI device
	pci="ahci-hd,/dev/zvol/$dataset/disk0 $pci"
	#Add Hostbridge and lpc as the first PCI devices
	pci="hostbridge lpc $pci"
	# return the list of pci devices
	echo $pci
}

# Start guest (combine load and boot)
__start() {
	local name="$2"
	local flag="$3"
	local pci=""
	local runmode="1"
	local pool="$(zfs list -H -t volume -o name | grep $name| grep disk0 | cut -d '/' -f1)"
	local dataset="$(zfs list -H -t volume -o name | grep $name | grep disk0 | cut -d '/' -f 1-3 | head -n1)"
	local loader="$(zfs get -H -o value iohyve:loader $dataset)"
	# Check if loader is UEFI
	if [ $loader = "uefi" ]; then
		__uefi "$name" "null.iso"
	fi
	# Check if guest exists
	if [ -d /iohyve/$pool/$name ] || [ -d /iohyve/$name ]; then
		# Check to make sure guest isn't running
		local running=$(pgrep -fx "bhyve: ioh-$name")
		if [ -z $running ]; then
			case "$flag" in
				-s)	runmode="0"	# single - start only once
					;;
				-a) 	runmode="2"	# always - persist regardless what
					;;
				*)	runmode="1"	# persist - persists until guest is powering off
					;;
			esac
			echo "Starting $name... (Takes 15 seconds for FreeBSD guests)"
			# Prepare and boot guest
			pci="$(__prepare_guest $name)"
			__boot "$name" "$runmode" "$pci"
		else
			echo "Guest is already running."
		fi
	else
		echo "Not a valid guest name"
	fi
}

# Start a UEFI enabled bhyve instance.
# This is experimental, use with caution.
__uefi() {
	local name="$2"
	local media="$3"
	local dataset="$(zfs list -H -t volume | grep $name | cut -d '/' -f 1-3 | head -n1)"
	local ram="$(zfs get -H -o value iohyve:ram $dataset)"
	local con="$(zfs get -H -o value iohyve:con $dataset)"
	local cpu="$(zfs get -H -o value iohyve:cpu $dataset)"
	local fw="$(zfs get -H -o value iohyve:fw $dataset)"
	local tap="$(zfs get -H -o value iohyve:tap $dataset)"
	local bargs="$(zfs get -H -o value iohyve:bargs $dataset | sed -e 's/_/ /g')"
	local pool="$(zfs list -H -t volume -o name | grep $name | cut -d '/' -f1)"
	# Create tap if needed
	if [ $tap != "tap0" ]; then
		# no need to create tap0, should be installed already via README
		# check to see if tap is already created before attempting to create new tap interface
		local tapif="$('ifconfig' -l | grep $tap | cut -c1)"
		if [ -z $tapif ]; then
			# create tap interface
			ifconfig $tap create
			ifconfig bridge0 addm $tap
		fi
	fi
	# Make sure everything is in order...
	if [ $fw = '-' ]; then
		echo "You must set a firmware file property to use UEFI..."
	fi
	if [ -z $media ]; then
		echo "You must enter at least a zero byte ISO for some OSs..."
		echo "EX: iohyve uefi winguest null.iso"
	fi
	# Check if guest exists
	if [ -d /iohyve/$pool/$name ] || [ -d /iohyve/$name ]; then
		# Check to make sure guest isn't running
		local running=$(pgrep -fx "bhyve: ioh-$name")
		if [ -z $running ]; then
			# The good stuff...
			bhyve -c $cpu $bargs -m $ram \
			        -s 0,hostbridge \
			        -s 3,ahci-cd,/iohyve/ISO/$media/$media \
			        -s 4,ahci-hd,/dev/zvol/$dataset/disk0,sectorsize=512 \
			        -s 10,virtio-net,$tap \
			        -s 31,lpc \
			        -l com1,/dev/${con}A \
			        -l bootrom,/iohyve/Firmware/$fw/$fw \
			        ioh-$name &
		else
			echo "Guest is already running."
		fi
	else
		echo "Not a valid guest name"
	fi
}

# Gracefully stop a guest
__stop() {
	local name="$2"
	local pool="$(zfs list -H | grep iohyve | cut -d '/' -f 1 | head -n1)"
	local pid=$(pgrep -fx "bhyve: ioh-$name")
	echo "Stopping $name..."
#	zfs set iohyve:persist=0 $pool/iohyve/$name
	kill $pid
#	sleep 20
#	bhyvectl --destroy --vm=ioh-$name
}

# Force kill -9 everyting matching $name and destroy
# THIS WILL KILL EVERYTHING MATCHING $NAME
__forcekill() {
	local name="$2"
	local pids="$(pgrep -f $name)"
	for apid in "$pids"; do
		kill -9 $apid
	done
	bhyvectl --destroy --vm=ioh-$name
}

# Gracefully shut down all guests via ACPI (Does not destroy)
__scram() {
	echo "Shutting down all guests..."
	local pids="$(pgrep -f ioh-)"
	for apid in "$pids"; do
		kill $apid
	done
	wait_for_pids $pids
}

# Destroy guest
__destroy() {
	local name="$2"
	local pool="$(zfs list -H | grep iohyve | cut -d '/' -f 1 | head -n1)"
	echo "Destroying $name..."
#	zfs set iohyve:persist=0 $pool/iohyve/$name
	bhyvectl --force-poweroff --vm=ioh-$name
	bhyvectl --destroy --vm=ioh-$name
}

# Rename the guest
__rename() {
	local name="$2"
	local newname="$3"
	local pool="$(zfs list -H -t volume | grep $name | cut -d '/' -f 1 | head -n1)"
	echo "Renaming $name to $newname..."
	zfs rename -f $pool/iohyve/$name $pool/iohyve/$newname
	zfs set iohyve:name=$newname $pool/iohyve/$newname
}

# Delete guest
__delete() {
	local name="$2"
	local datasets="$(zfs list -H -t filesystem -o name | grep iohyve | grep $name)"
	read -p "Are you sure you want to delete $name and all associated datasets [Y/N]? " an </dev/tty
	case "$an" in
		y|Y) for d in $datasets; do zfs destroy -rR $d; done
		;;
		*) echo "Not deleted..."
		;;
	esac
}

# Set ZFS properties
__set() {
	local name="$2"
	local pool="$(zfs list -H -t volume | grep $name | cut -d '/' -f 1 | head -n1)"
	shift 2
	for arg in "$@"; do
		local prop="$(echo $arg | cut -d '=' -f1)"
		local val="$(echo $arg | cut -d '=' -f2)"
		if [ $prop = "bargs" ]; then
			local sval="$(echo $val | cut -d '"' -f2 | sed -e 's/ /_/g')"
			echo "Setting $name $prop=$val..."
			zfs set iohyve:$prop=$sval $pool/iohyve/$name
		elif [ $prop = "description" ]; then
			local sval="$(echo $val | cut -d '"' -f2)"
			echo "Setting $name $prop=$val..."
			zfs set "iohyve:$prop=$sval" $pool/iohyve/$name
		else
			echo "Setting $name $prop=$val..."
			zfs set iohyve:$prop=$val $pool/iohyve/$name
		fi
	done
}

# Set ZFS props [retro style]
__oldset() {
	local name="$2"
	local propval="$3"
	local prop="$(echo $propval | cut -d '=' -f1 )"
	local sprop="$(echo $propval | cut -d '"' -f2 | sed -e 's/ /_/g')"
	local pool="$(zfs list -H -t volume | grep $name | cut -d '/' -f 1 | head -n1)"
	echo "Setting $name prop $propval..."
	if [ $prop = "description" ]; then
		zfs set iohyve:$sprop $pool/iohyve/$name
	elif [ $prop = "bargs" ]; then
		zfs set iohyve:$sprop $pool/iohyve/$name
	else
		zfs set iohyve:$propval $pool/iohyve/$name
	fi
}

# Get ZFS props
__get() {
	local name="$2"
	local prop="$3"
	local pool="$(zfs list -H -t volume | grep $name | cut -d '/' -f 1 | head -n1)"
	echo "Getting $name prop $prop..."
	zfs get -H -o value iohyve:$prop $pool/iohyve/$name
}

# Remove a PCIDEV property
__rmpci() {
	local name="$2"
	local prop="$3"
	local pciprop="$(echo "$prop" | grep pcidev:)"
	local pool="$(zfs list -H -t volume | grep $name | cut -d '/' -f 1 | head -n1)"
	# Make sure it's a valid pcidev property as to not shoot foot
	if [ -z $pciprop ]; then
		echo "Not a valid PCIDEV property"
	else
		read -p "Are you sure you want to remove $prop [Y/N]? " an </dev/tty
		case "$an" in
			y|Y) zfs inherit  -r iohyve:$prop $pool/iohyve/$name
			;;
			*) echo "Not removed..."
			;;
		esac
	fi
}

# Get all ZFS props
__getall() {
	local name="$2"
	local pool="$(zfs list -H -t volume | grep $name | grep disk0 | cut -d '/' -f 1 | head -n1)"
	echo "Getting $name props..."
	zfs get -H all $pool/iohyve/$name | grep iohyve: | cut -w -f2-3 | cut -c8- | column -t
}

# Fix legacy bhyve arguments
__fixbargs() {
	local name="$2"
	local pool="$(zfs list -H -t volume | grep $name | grep disk0 | cut -d '/' -f 1 | head -n1)"
	echo "Setting default bargs flags for bhyve to $name..."
	zfs set iohyve:bargs=-A_-H_-P $pool/iohyve/$name
}

# Add a new disk to guest
__add() {
	local name="$2"
	local size="$3"
	local pool="$(zfs list -H -t volume | grep $name | cut -d '/' -f 1 | head -n1)"
	# optionally allow the pool for the new disk to be specified. If not set, its set to $pool
	local newpool="${4-$pool}"
	# Find the last disk number and increment one
	local lastdisk="$(zfs list -H | grep $name | grep disk | cut -d '/' -f4 | cut -f1 | \
		sort -V | cut -c5- | tail -n1)"
	local newdisk="$(expr $lastdisk + 1)"
	echo "Creating new zvol for $name..."
	zfs create $newpool/iohyve/$name 2> /dev/null
	zfs create -V $size -o volmode=dev $newpool/iohyve/$name/disk$newdisk
	# Find the last pcidev and increment by one
	local lastpci="$(zfs get -H all | grep iohyve/$name | grep pcidev | cut -f2 | \
		cut -d ':' -f3 | sort -V | tail -n1)"
	if [ -z $lastpci ]; then
		local newpci='1'
	else
		local newpci="$(expr $lastpci + 1)"
	fi
	zfs set iohyve:pcidev:$newpci=ahci-hd,/dev/zvol/$newpool/iohyve/$name/disk$newdisk $pool/iohyve/$name
}

# Remove disk from guest
__remove() {
	local name="$2"
	local disk="$3"
	local pool="$(zfs list -H -o name | grep $name | grep $disk | cut -d '/' -f 1)"
	local pciprop="$(zfs get -H all $pool/iohyve/$name | grep pcidev | grep $disk | cut -f2 )"
	# Make sure it's a valid pcidev property as to not shoot foot
	if [ -z $pciprop ]; then
		echo "Not a valid PCIDEV property"
	else
		read -p "Are you sure you want to remove $disk from $name [Y/N]? " an </dev/tty
		case "$an" in
			y|Y)	zfs inherit  -r $pciprop $pool/iohyve/$name
				zfs destroy $pool/iohyve/$name/$disk
			;;
			*) echo "Not removed..."
			;;
		esac
	fi
}

# Resize a disk
__resize(){
	local name="$2"
	local disk="$3"
	local size="$4"
	local pool="$(zfs list -H -o name | grep $name | grep $disk | cut -d '/' -f 1)"
	# Check if guest exists
	echo "Resizing $disk to $size"
	if [ -d /iohyve/$pool/$name ] || [ -d /iohyve/$name ]; then
		# Check to make sure guest isn't running
		local running=$(pgrep -fx "bhyve: ioh-$name")
		if [ -z $running ]; then
			zfs set volsize=$size $pool/iohyve/$name/$disk
		else
			echo "Please stop the guest first"
		fi
	else
		echo "Not a valid guest name"
	fi
}

# List disks for a guest
__disks() {
	local name="$2"
	local pool="$(zfs list -H | grep iohyve | cut -d '/' -f 1 | head -n1)"
	if [ -z $name ]; then
		echo "You must enter a guest name."
	elif [ -d /iohyve/$pool/$name ] || [ -d /iohyve/$name ]; then
		(
		echo "Listing disks for $name..."
		printf "diskN\tSize\n"
		zfs list -H -o name,volsize | grep -E "iohyve.*$name.*disk" | \
			cut -d '/' -f4
		) | column -t
	else
		echo "Not a valid guest name"
	fi
}

# Snapshot a guest
__snapguest() {
	local fullsnap="$2"
	local name="$(echo $fullsnap | cut -d '@' -f1)"
	local pool="$(zfs list -H -t volume | grep $name | grep disk0 | cut -d '/' -f 1 | head -n1)"
	echo "Taking snapshot $fullsnap"
	# Check if guest exists
	if [ -d /iohyve/$pool/$name ] || [ -d /iohyve/$name ]; then
		zfs snap -r $pool/iohyve/$fullsnap
	else
		echo "Not a valid guest name"
	fi
}

# Rollback guest
__rollguest() {
	local fullsnap="$2"
	local name="$(echo $fullsnap | cut -d '@' -f1)"
	local pool="$(zfs list -H -t volume | grep $name | grep disk0 | cut -d '/' -f 1 | head -n1)"
	local snap="$(echo $fullsnap | cut -d '@' -f2)"
	local disklist="$(zfs list -H | grep iohyve | grep $name | grep disk | \
				cut -f1 | cut -d '/' -f4-)"
	# Check if guest exists
	echo "Rolling back to $fullsnap"
	if [ -d /iohyve/$pool/$name ] || [ -d /iohyve/$name ]; then
		# Check to make sure guest isn't running
		local running=$(pgrep -fx "bhyve: ioh-$name")
		if [ -z $running ]; then
			zfs rollback -rR $pool/iohyve/$fullsnap
			for disk in $disklist ; do
				zfs rollback -rR $pool/iohyve/$name/$disk@$snap
			done
		else
			echo "Please stop the guest first"
		fi
	else
		echo "Not a valid guest name"
	fi
}

# Clone a guest
__cloneguest() {
	local name="$2"
	local cname="$3"
	local description="$(date | sed -e 's/ /_/g')"
	local pool="$(zfs list -H -t volume | grep $name | grep disk0 | cut -d '/' -f 1 | head -n1)"
	# Check if guest exists
	echo "Cloning $name to $cname"
	if [ -d /iohyve/$pool/$name ] || [ -d /iohyve/$name ]; then
		# Check to make sure guest isn't running
		local running=$(pgrep -fx "bhyve: ioh-$name")
		if [ -z $running ]; then
			# Take snapshot
			zfs snap -r $pool/iohyve/$name@$cname
			# zfs send that snap and desendants then receive to cname
			zfs send -R $pool/iohyve/$name@$cname | \
			zfs recv $pool/iohyve/$cname
			# clean up
			zfs destroy -rR $pool/iohyve/$name@$cname
			zfs destroy -rR $pool/iohyve/$cname@$cname
			# rename the guest
			zfs set iohyve:name=$cname $pool/iohyve/$cname
			zfs set iohyve:description=$description $pool/iohyve/$cname
		else
			echo "Please stop the guest first"
		fi
	else
		echo "Not a valid guest name"
	fi
}

# List all the snapshots
__snaplist() {
	zfs list -H -t snap | grep iohyve | grep -v disk | cut -f1 | cut -d '/' -f3
}

# List taps in use
__taplist() {
	local guestlist="$(zfs list -H -o name -t volume | grep iohyve | cut -d'/' -f1-3)"
	echo "Listing all network taps:"
	for i in $guestlist ; do
		conprop="$(zfs get -H -o value iohyve:tap $i)"
		printf $i'......'$conprop'\n'
	done
}

# List active taps in use
__activetaps() {
  echo "Listing active network taps..."
	ls /dev | grep tap
}

# List consoles in use
__conlist() {
	local pool="$(zfs list -H | grep iohyve | cut -d '/' -f 1 | head -n1)"
	local guestlist="$(zfs list -H | grep iohyve | grep -v ISO | grep -v disk | grep -v Firmware | sed 1d | cut -f1 | cut -d '/' -f3)"
	(
	printf 'Guest\tConsole\n'
	for guest in $guestlist; do
		local con="$(zfs get -H -o value iohyve:con $pool/iohyve/$guest)"
		printf $guest'\t'$con'\n'
	done
	) | column -t
}

# Run console
__console() {
	local name="$2"
	local pool="$(zfs list -H -t volume | grep $name | grep disk0 | cut -d '/' -f 1-3 | head -n1)"
	local con="$(zfs get -H -o value iohyve:con $pool)"
	echo "Starting console on $name..."
	echo "~~. to escape console [uses cu(1) for console]"
	cu -l /dev/${con}B -s 9600
}

# Reset all consoles. This kills the cu(1)
__conreset() {
	killall cu
}

# Print help page
__help() {
cat << 'EOT'
iohyve  version
        setup pool=[poolname] kmod=[0/1] net=[interface]
        list
	info [-d]
        isolist
	fwlist
        fetch [URL]
	cpiso [path]
        renameiso [ISO] [newname]
	rmiso [ISO]
        fetchfw [URL]
        cpfw [path]
        renamefw [firmware] [newname]
        rmfw [firmware]
        create [name] [size]
        install [name] [ISO]
        load [name] [path/to/bootdisk]
        boot [name] [runmode] [pcidevices]
        start [name] [-s | -a]
	stop [name]
	forcekill [name]
        scram
        destroy [name]
	rename [name] [newname]
        delete [name]
        set [name] [prop1=value] [prop2=value]...
        get [name] [prop]
	rmpci [name] [pcidev:N]
        getall [name]
	add [name] [size] [[pool]]
	remove [name] [diskN]
	resize [name] [diskN] [size]
	disks [name]
	snap [name]@[snapshotname]
	roll [name]@[snapshotname]
	clone [name] [clonename]
	snaplist
        taplist
	activetaps
	conlist
        console [name]
        conreset
        help
EOT
}

if [ -z "$1" ] ; then
    __help
    exit 0
fi

if [ $(__readonly_cmd "$1") != "0" -a "$(whoami)" != "root" ] ; then
    echo "The $1 command needs root credentials!"
    exit 1
fi

__parse_cmd "$@"
