#!/bin/sh

# List consoles in use
__conlist() {
	local pool="$(zfs list -H | grep iohyve | cut -d '/' -f 1 | head -n 1)"
	local guestlist="$(zfs list -H | grep iohyve | grep -v -e ISO -e disk -e Firmware | sed 1d | cut -f 1 | cut -d '/' -f 3)"
	(
	printf 'Guest\tConsole\n'
	for guest in $guestlist; do
		local con="$(zfs get -H -o value iohyve:con $pool/iohyve/$guest)"
		printf $guest'\t'$con'\n'
	done
	) | column -t
}

# Run console
__console() {
	local name=$2
	if [ -z "$name" ]; then
		printf "missing argument\nusage:\n"
		printf "\tconsole <name>\n"
		exit 1
	fi

	local pool="$(zfs list -H -t volume | grep iohyve/$name.*disk0 | cut -d '/' -f 1-3 | head -n 1)"
	local con="$(zfs get -H -o value iohyve:con $pool)"
	echo "Starting console on $name..."
	echo "~~. to escape console [uses cu(1) for console]"
	cu -l /dev/${con}B -s 9600
}

# Reset all consoles. This kills the cu(1)
__conreset() {
    # XXX This also kills cu(1) processes not started by iohyve.
	killall cu
}
