#!/bin/sh

# List taps in use
__tap_list() {
	local guestlist="$(zfs list -H -o name -t volume | grep iohyve | cut -d'/' -f1-3)"
	echo "Listing all network taps:"
	for i in $guestlist ; do
		conprop="$(zfs get -H -o value iohyve:tap $i)"
		printf $i'......'$conprop'\n'
	done
}

# List active taps in use
__tap_active_list() {
  echo "Listing active network taps..."
	ls /dev | grep tap
}
